### ISSUE TITLE
Create a console interface for commandline implementations

### ISSUE THREAD

**Issue by ilhnctn** [biberlabs/zf2-boilerplate#24]

**Comment by hkulekci** [comment]
Are there more information in this issue? What will you do? What do you think about structure? Maybe you could add some link about best practices. @ilhnctn

**Comment by ilhnctn** [comment]
I would explain the scenario in mind but just at that time faced an installition problem, i will explain the plan in a moment. Also you can kindly share your opinions to improve a better product @hkulekci

**Comment by edigu** [comment]
Dupe of last task of #5
